language: java
jdk:
 - oraclejdk8
branches:
  except:
    - travis
notifications:
  irc:
    channels:
      - "chat.freenode.net#craftercms"
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
addons:
  sonarqube: true
env:
  global:
    - secure: "m6Jpgc9LmHpNPFGJrdM4X6Gzye4mZp5hr2dv/JKDwnFKn7jZz80Tr9XzlqHtZt3d5DmI+nwZGp+UfMiJAfSMQIv81J+dl92+7XfdMK06SimV7433A2Ltrsn5L0H7TloBTmn/8uKOz2Zc2TSjHpklCYckrfgArbDq22P31JtkpBw="
    - secure: "tJ7qrpMhTexwOXUE2eSNDUZO4XL8DyKdbqyyU0i8Q+H/9IRPAgn7Tbmvxd4yU11b3dUuisNlh6nlQLedwcSXzukK4rzr6r+aWv6LRuH0F0ikF1/Sz/FHeI+b8W1JZAa+Yxp4P9X05pxImJ/PO5NbVhB3cnQ4T3K37NC+UPlSsg8="
    - secure: "cR8kcJLplpqo9GcC/pylT1Aw9LoFRYOMvut/cJbdRzky0cBW1BsDRy7hT1QslUmsl0GeutackpJySXmfP+R3df6xKGvv1AT0w+QKveDWriSksYQk/+cIMdlwlHnsDfcSsMZTTOyewE8J9V1HLfsrAitwT6CTJ4QV9rl/bOaX2RI="
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script:
  # other script steps might be done before running the actual SonarQube analysis
    - mvn deploy --settings target/travis/settings.xml
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
